spring:
  config:
    activate:
      on-profile: action
  #H2 Setting
  datasource:
    url: jdbc:h2:tcp://localhost/~/book-chat
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #Spring Data JPA Setting
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    open-in-view: false


  jackson:
    parser:
      allow-unquoted-control-chars: true

token:
  secret: 'test'
  accessTokenExpiredTime: 1800000
  refreshTokenExpiredTime: 1209600000
  oauth2:
    authorizaedRedirectUris:
      - http://localhost:8080

book:
  api:
    header: 'KakaoAK test'
    uri: test

aws:
  s3:
    accessKey: testetsttest
    secretKey: testestsetst
    region: ap-northeast-2