spring:
  config:
    activate:
      on-profile: action
  #H2 Setting
  datasource:
    url: jdbc:h2:tcp://localhost/~/book-chat
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #Spring Data JPA Setting
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    open-in-view: false

  jackson:
    parser:
      allow-unquoted-control-chars: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
book:
  api:
    header: 'KakaoAK test'
    uri: test

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2

aws:
  s3:
    accessKey: testetsttest
    secretKey: testestsetst
    region: ap-northeast-2
    imageBucketUrl: 'https://testbucket/testlink/testfile'
    bucketName: 'test-bucket'

oauth2:
  kakaoURI: 'https://kauth.kakao.com/.well-known/jwks.json'
  googleURI: