version: '3'

services:
  app:
    container_name: spring
    image: openjdk:11-jdk
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - ./gradlew bootRun
    restart: always

  nginx:
    container_name: nginx
    image: ubuntu/nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/nginx.conf
      - ./nginx/geoip.conf:/etc/nginx/conf.d/geoip.conf
    #      - ./nginx/geoip_update.sh:/
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - apt-get update &&
        apt-get install -y libnginx-mod-http-geoip geoip-database git wget python3-pip python-is-python3 &&
        pip install pygeoip &&
        pip install ipaddr &&
        apt-get install -y cron &&
        cd opt &&
        git clone https://github.com/sherpya/geolite2legacy &&
        mkdir /opt/geolite2legacy/maxmind-geo &&
        cd ./geolite2legacy/maxmind-geo &&
        wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key={}&suffix=zip" -O ./GeoLite2-Country-CSV.zip &&
        cd /opt/geolite2legacy &&
        ./geolite2legacy.py -i ./maxmind-geo/GeoLite2-Country-CSV.zip -f ./geoname2fips.csv -o ./maxmind-geo/GeoIP.dat &&
        mv -f ./maxmind-geo/GeoIP.dat /usr/share/GeoIP