name: bookchat-service-build&deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  BUILD_DEPLOY:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      actions: read
    env:
     working-directory: ./back
     APPLICATION: ${{secrets.PRODUCTION}}

    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
      working-directory: ${{ env.working-directory }}
      
#     - name: Create Configuration File
#       run: echo "${{ env.APPLICATION }}" > ./back/src/main/resources/application.yml
#       shell: bash
      
#     - name: Substitute Configuration File
#       uses: actions/upload-artifact@v3
#       with: 
#         name: application.yml
#         path: ./back/src/main/resources/application.yml
      
    - name: Build with Gradle
      run: ./gradlew clean build -x test -x asciidoctor
      shell: bash
      working-directory: ${{ env.working-directory }}
