name: bookchat-service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
     working-directory: ./back

    steps:
    
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
      working-directory: ${{ env.working-directory }}

    - name: Build with Gradle
      run: ./gradlew clean build -x test -x asciidoctor
      shell: bash
      working-directory: ${{ env.working-directory }}
