name: bookchat-service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
     working-directory: ./back

    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
      working-directory: ${{ env.working-directory }}

    - name: Test with Gradle
      run: ./gradlew clean test -x asciidoctor
      shell: bash
      working-directory: ${{ env.working-directory }}
      
    - name: tt
      run: cd back && cd build && ls -al && cd test-results && ls -al && cd test && ls -al
      shell: bash
      
    - name: Test Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "build/test-results/test/**/*.xml"
        
    - name: Build with Gradle
      run: ./gradlew clean build -x test -x asciidoctor
      shell: bash
      working-directory: ${{ env.working-directory }}

    - name: Get Current Time
      uses: josStorer/get-current-time@v2.0.0
      id: current-time
      with:
        format: YYYY-MM-DD-HH-mm-ss
        utcOffset: "+09:00"
        
    - name: Show Current Time
      run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
      shell: bash
