name: bookchat-service-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  TEST:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      actions: read
    env:
     working-directory: ./back
     APPLICATION: ${{secrets.TEST}}

    steps:
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
      working-directory: ${{ env.working-directory }}
      
    - name: Test
      run: pwd
      shell: bash
      
    - name: Create Configuration File
      run: touch ./back/src/main/resource/application.yml && echo "${{ env.APPLICATION }}" > ./back/src/main/resource/application.yml
      shell: bash
      
    - name: Substitute Configuration File
      uses: actions/upload-artifact@v3
      with: 
        name: application.yml
        path: ./back/src/main/resource/application.yml
      

    - name: Test with Gradle
      run: ./gradlew clean test -x asciidoctor
      shell: bash
      working-directory: ${{ env.working-directory }}
      
    - name: Test Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: '**/build/test-results/test/TEST-*.xml'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
